name: Auto Commit and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Change to your Go version

      - name: Configure Git
        run: |
          git config --global user.name "your-github-username"
          git config --global user.email "your-email@example.com"

      - name: Make Changes and Commit
        run: |
          echo "// Auto update on $(date)" >> update.log
          git add .
          git commit -m "Automated update"
          git push origin main
